packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd

confirmModulesPurge: false
allowBuilds:
  esbuild: true
  protobufjs: true
  sharp: true
  workerd: true
