name = "verisight-backend"
main = "src/index.ts"
compatibility_date = "2026-05-24"
workers_dev = true

[vars]
MODEL_URL = "https://media.githubusercontent.com/media/LordShivam18/AI-Based-Fake-News-Detector/main/apps/frontend/public/model.onnx"

[observability.logs]
enabled = false
invocation_logs = true
